# Python Built-in Functions

print(abs(-1))
print(all([1, 2, 3, 4, 5, 6, 7,]))
print(any([0, 0, 0, 1]))
print('------')
print(bool(''))
print(bool(' '))
print('------')
print(bool(1))
print(bool(0))
print('------')
print(chr(65))
print(chr(97))
print('------')
print(ord('A'))
print(ord('a'))
print('------')
print(dict([('one', '1'), ('two', 2)]))
print('------')
print(float(10))
print(int(10.1))
print('------')
print(set('aabbbccc'))
print(len(set('aabbbccc')))
